### ISSUE TITLE
Play again with the same group!

### ISSUE THREAD

**Issue by bromeostasis** [mwbennett/emojiphone#16]
This feedback was received in the prototype, but people are going to want to play with the same group over and over!

**Open Questions**

* Can anyone in the group re-initiate a game or just the original initiator?

**Tasks**

- [x] Add games table (id, restarted, token, tokenExpiry)
- [x] Change turns.gameId to be a foreign key
- [x] Create a "game" during setup
- [x] Add method to setup new game outside conversation (get userIds by gameId, pass to setupGame, takeFirstTurn)
- [x] Convert endgame message to conversation
- [x] Add option to restart to endgame conversation
- [ ] Mark game as restarted
- [ ] Prevent game from being restarted if already restarted

**Comment by bromeostasis** [comment]
Anyone should be able to re-initiate the game, but we need a way to ensure it doesn't happen multiple times.. Does that mean a text when the game begins? Could tie in to #17 ?

**Comment by bromeostasis** [comment]
Alternatively, we just text everyone for this specific case.

**Comment by bromeostasis** [comment]
Alternatively alternatively, we mark down that a game has been restarted?

**Comment by bromeostasis** [comment]
Hmm, we could make a `game` table that `gameId` points to. That would also work for #41 .
