### ISSUE TITLE
Aggregate/create end-game message

### ISSUE THREAD

**Issue by bromeostasis** [mwbennett/emojiphone#8]
After a round is completed, we need to aggregate the full game log to be able to share it with all participants (#9)

Screenshot from beta:

![image](https://user-images.githubusercontent.com/3764641/54651451-55aeba00-4a89-11e9-84f3-72645023b4bb.png)
 
**Tasks**

- [x] Add function that gets all users' names & messages given a gameId
- [x] Exclude any null messages
- [ ] Format names and messages into readable text string (separate function?!)

**Out of scope**

Any part of the conversation, we can just use an existing "game" from the db to test!

**Dependencies**

#7
